export enum TasksActionType {
	FETCH_WEATHER = 'FETCH_WEATHER',
	STORE_WEATHER = 'STORE_WEATHER',
	ERROR_WEATHER = 'ERROR_WEATHER',

	CREATE_TASK = 'CREATE_TASK',
	SET_TASKS = 'SET_TASKS',
	UPDATE_TASK = 'UPDATE_TASK',
	COMPLETE_TASK = 'COMPLETE_TASK',
	DELETE_TASK = 'DELETE_TASK'
}
